{% set name = "itmo_fs" %}
{% set version = "0.3.4.dev1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"


requirements:
  build:
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python
    - numpy >=1.25.2
    - scipy >=1.11.4
    - scikit-learn >=1.4.2,<1.8
    - imbalanced-learn >=0.14,<0.15
    - qpsolvers >=4,<5

test:
  imports:
    - ITMO_FS

about:
  home: https://github.com/ctlab/ITMO_FS
  license: BSD-3-Clause
  summary: Python Feature-Selection toolbox from ITMO University.
